### ISSUE TITLE
Option 2 Error

### ISSUE THREAD

**Issue by mgifford** [OpenAssessItToolkit/openassessit#21]
This looks like it's an external problem with jinja2.

```
$ pip install -r requirements.txt
Collecting Jinja2==2.10 (from -r requirements.txt (line 1))
  Could not fetch URL https://pypi.python.org/simple/jinja2/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement Jinja2==2.10 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for Jinja2==2.10 (from -r requirements.txt (line 1))
```

**Comment by joelhsmith** [comment]
Thanks Mike!  Since you are on the local option for this, can you run this for me too?:

node --version
lighthouse --version
python --version
pip --version

**Comment by mgifford** [comment]
$ docker --version
Docker version 18.09.2, build 6247962
$ node --version
v10.13.0
$  lighthouse --version
4.2.0
$  python --version
Python 2.7.11
$  pip --version
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)

Thanks Joel!

**Comment by joelhsmith** [comment]
I am trying to keep the project backward compatible with Python 2.7.  If it is a certificate thing then its sorta a environment issue that will be diff from person to person based on a variety of configurations.  https://github.com/pypa/pip/issues/5226 

I think if you use Python3 and Pip3 instead it will work.  They both might already be installed on your computer. Try `python3 --version` and `pip3 --version`.  If they come back as Python 3.7+ and Pip3 18.0+ will probably work fine.

**Comment by mgifford** [comment]
Looks like I am making progress now.  This seems to be working: 
$ pip3 install -r requirements.txt

Now running:

$ python --version
Python 2.7.11
$ python3 --version
Python 3.6.0
$ pip --version
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (python 2.7)
$ pip3 --version
pip 19.0.3 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip (python 3.6)

But I think I need to get rid of the other versions.. Still isn't quite working for me.

**Comment by joelhsmith** [comment]
Its totally fine to have multiple versions. Just run `python3` instead of `python` when you type in commands.

You could also use the run.sh file it has a script that will run all three modules.  It has `python3` indicated in there already.

```bash
sh run.sh lighthouse https://cats.com catshomey chrome
```

**Comment by mgifford** [comment]
Good to know about python & python3

I might well have a buggy system....  Tried too many hacky things over too many years.  Anyways:

```
$ sh run.sh lighthouse https://cats.com catshomey chrome
: command not found
run.sh: line 29: syntax error: unexpected end of file
```

**Comment by joelhsmith** [comment]
Thanks for persevering with me on this! I really appreciate it. 

Lets try to set you up on a [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtualenv/). There are a ton of ways to set up virtual environments in Python, but this virtualenv is really easy to set up. It think that will remove a lot of variables between setups that will help me reproduce and debug. 

Install one:
```bash
python3 -m pip install --user virtualenv
```
Create one in the project:
```bash
python3 -m virtualenv env
```
Activate it
```bash
source env/bin/activate
```

Then install the prerequisites from [Option 2](https://github.com/OpenAssessItToolkit/openassessit#option-2-manually-install-prerequisites-and-run-locally) like so:

I am making a few assumptions here on directory structure. 

From the `openassessit` dir

```bash
pip3 install -f requirements.txt
```
Run lighthouse
```
lighthouse https://cats.com --only-categories=accessibility --disable-device-emulation --output=json --output-path=tmp/catsaudit.json --chrome-flags="--headless --window-size=1300,600"
```
Run markdown
```bash
python3 -m openassessit.markdown --input-file="tmp/catsaudit.json" --output-file="tmp/catsaudit.md" --user-template-path="../openassessit_templates/templates"
```
Run capture to take screenshots
```bash
python3  -m openassessit.capture --input-file="catsaudit.json" --assets-dir="assets/" --sleep=1 --driver=chrome
```
Note: if the markdown script works, but capture fails, its probably an issue with the webdriver install prereq.

Convert to pretty html
```bash
python3 -m openassessit.markdown --input-file="tmp/catsaudit.md" --output-file="tmp/catsaudit.html" --user-template-path="../openassessit_templates/templates"
```

If it fails, but generates any log files, can you put them up in a gist?

If all that worked, then the run.sh will prolly work now too.

If you run it again, you would just run `source env/bin/activate` again to activate the same one. you will not need to reinstall everything.  If all this works, it would just be ready for use.

**Comment by mgifford** [comment]
Option 1 is working now so I'm going to leave this.  

I did run into some errors walking through this.

```
$ pip3 install -f ./requirements.txt
ERROR: You must give at least one requirement to install (maybe you meant "pip install ./requirements.txt"?)
```

and also:

```
$ python3 -m openassessit.markdown --input-file="tmp/catsaudit.json" --output-file="tmp/catsaudit.md" --user-template-path="../openassessit_templates/templates"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mikegifford/openassessit/openassessit/markdown.py", line 3, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
```

I don't know if it is worth pursuing this though as I have a working solution for now.

**Comment by joelhsmith** [comment]
Oh cool.  My bad, the `-f` is a typo.  It should have been `-r`.  The Jinja error would have came from the requirements.txt not installing.  Thanks for your help on these Mike!

**Comment by mgifford** [comment]
Excellent.. Let me know when you are ready for me to start promoting it :)
